//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceClient
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://www.tempuri.org/")]
    public partial class Usuario : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private string SurnameField;
        
        private string LoginField;
        
        private string EmailField;
        
        private string PasswordField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioDto", Namespace="http://www.tempuri.org/")]
    public partial class UsuarioDto : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private string SurnameField;
        
        private string EmailField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.tempuri.org/", ConfigurationName="ServiceClient.IUsuario")]
    public interface IUsuario
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/IICrud`2/Create", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.CreateResponse> CreateAsync(ServiceClient.CreateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/IICrud`2/Read", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.ReadResponse> ReadAsync(ServiceClient.ReadRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/IICrud`2/ReadAll", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.UsuarioDto[]> ReadAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/IICrud`2/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.UpdateResponse> UpdateAsync(ServiceClient.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/IICrud`2/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.tempuri.org/IUsuario/GetIdUsuario", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceClient.GetIdUsuarioResponse> GetIdUsuarioAsync(ServiceClient.GetIdUsuarioRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Create", Namespace="http://www.tempuri.org/", Order=0)]
        public ServiceClient.CreateRequestBody Body;
        
        public CreateRequest()
        {
        }
        
        public CreateRequest(ServiceClient.CreateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org/")]
    public partial class CreateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.Usuario entity;
        
        public CreateRequestBody()
        {
        }
        
        public CreateRequestBody(ServiceClient.Usuario entity)
        {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateResponse", Namespace="http://www.tempuri.org/", Order=0)]
        public ServiceClient.CreateResponseBody Body;
        
        public CreateResponse()
        {
        }
        
        public CreateResponse(ServiceClient.CreateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org/")]
    public partial class CreateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.UsuarioDto CreateResult;
        
        public CreateResponseBody()
        {
        }
        
        public CreateResponseBody(ServiceClient.UsuarioDto CreateResult)
        {
            this.CreateResult = CreateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Read", Namespace="http://www.tempuri.org/", Order=0)]
        public ServiceClient.ReadRequestBody Body;
        
        public ReadRequest()
        {
        }
        
        public ReadRequest(ServiceClient.ReadRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org/")]
    public partial class ReadRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public ReadRequestBody()
        {
        }
        
        public ReadRequestBody(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadResponse", Namespace="http://www.tempuri.org/", Order=0)]
        public ServiceClient.ReadResponseBody Body;
        
        public ReadResponse()
        {
        }
        
        public ReadResponse(ServiceClient.ReadResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org/")]
    public partial class ReadResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.UsuarioDto ReadResult;
        
        public ReadResponseBody()
        {
        }
        
        public ReadResponseBody(ServiceClient.UsuarioDto ReadResult)
        {
            this.ReadResult = ReadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://www.tempuri.org/", Order=0)]
        public ServiceClient.UpdateRequestBody Body;
        
        public UpdateRequest()
        {
        }
        
        public UpdateRequest(ServiceClient.UpdateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org/")]
    public partial class UpdateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.Usuario entity;
        
        public UpdateRequestBody()
        {
        }
        
        public UpdateRequestBody(ServiceClient.Usuario entity)
        {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://www.tempuri.org/", Order=0)]
        public ServiceClient.UpdateResponseBody Body;
        
        public UpdateResponse()
        {
        }
        
        public UpdateResponse(ServiceClient.UpdateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org/")]
    public partial class UpdateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceClient.UsuarioDto UpdateResult;
        
        public UpdateResponseBody()
        {
        }
        
        public UpdateResponseBody(ServiceClient.UsuarioDto UpdateResult)
        {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIdUsuarioRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIdUsuario", Namespace="http://www.tempuri.org/", Order=0)]
        public ServiceClient.GetIdUsuarioRequestBody Body;
        
        public GetIdUsuarioRequest()
        {
        }
        
        public GetIdUsuarioRequest(ServiceClient.GetIdUsuarioRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org/")]
    public partial class GetIdUsuarioRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nome;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string login;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Email;
        
        public GetIdUsuarioRequestBody()
        {
        }
        
        public GetIdUsuarioRequestBody(string nome, string login, string Email)
        {
            this.nome = nome;
            this.login = login;
            this.Email = Email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIdUsuarioResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIdUsuarioResponse", Namespace="http://www.tempuri.org/", Order=0)]
        public ServiceClient.GetIdUsuarioResponseBody Body;
        
        public GetIdUsuarioResponse()
        {
        }
        
        public GetIdUsuarioResponse(ServiceClient.GetIdUsuarioResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.tempuri.org/")]
    public partial class GetIdUsuarioResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetIdUsuarioResult;
        
        public GetIdUsuarioResponseBody()
        {
        }
        
        public GetIdUsuarioResponseBody(int GetIdUsuarioResult)
        {
            this.GetIdUsuarioResult = GetIdUsuarioResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IUsuarioChannel : ServiceClient.IUsuario, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class UsuarioClient : System.ServiceModel.ClientBase<ServiceClient.IUsuario>, ServiceClient.IUsuario
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public UsuarioClient() : 
                base(UsuarioClient.GetDefaultBinding(), UsuarioClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IUsuario_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsuarioClient(EndpointConfiguration endpointConfiguration) : 
                base(UsuarioClient.GetBindingForEndpoint(endpointConfiguration), UsuarioClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsuarioClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(UsuarioClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsuarioClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(UsuarioClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public UsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.CreateResponse> ServiceClient.IUsuario.CreateAsync(ServiceClient.CreateRequest request)
        {
            return base.Channel.CreateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.CreateResponse> CreateAsync(ServiceClient.Usuario entity)
        {
            ServiceClient.CreateRequest inValue = new ServiceClient.CreateRequest();
            inValue.Body = new ServiceClient.CreateRequestBody();
            inValue.Body.entity = entity;
            return ((ServiceClient.IUsuario)(this)).CreateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.ReadResponse> ServiceClient.IUsuario.ReadAsync(ServiceClient.ReadRequest request)
        {
            return base.Channel.ReadAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.ReadResponse> ReadAsync(int id)
        {
            ServiceClient.ReadRequest inValue = new ServiceClient.ReadRequest();
            inValue.Body = new ServiceClient.ReadRequestBody();
            inValue.Body.id = id;
            return ((ServiceClient.IUsuario)(this)).ReadAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.UsuarioDto[]> ReadAllAsync()
        {
            return base.Channel.ReadAllAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.UpdateResponse> ServiceClient.IUsuario.UpdateAsync(ServiceClient.UpdateRequest request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.UpdateResponse> UpdateAsync(ServiceClient.Usuario entity)
        {
            ServiceClient.UpdateRequest inValue = new ServiceClient.UpdateRequest();
            inValue.Body = new ServiceClient.UpdateRequestBody();
            inValue.Body.entity = entity;
            return ((ServiceClient.IUsuario)(this)).UpdateAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceClient.GetIdUsuarioResponse> ServiceClient.IUsuario.GetIdUsuarioAsync(ServiceClient.GetIdUsuarioRequest request)
        {
            return base.Channel.GetIdUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceClient.GetIdUsuarioResponse> GetIdUsuarioAsync(string nome, string login, string Email)
        {
            ServiceClient.GetIdUsuarioRequest inValue = new ServiceClient.GetIdUsuarioRequest();
            inValue.Body = new ServiceClient.GetIdUsuarioRequestBody();
            inValue.Body.nome = nome;
            inValue.Body.login = login;
            inValue.Body.Email = Email;
            return ((ServiceClient.IUsuario)(this)).GetIdUsuarioAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUsuario_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IUsuario_soap))
            {
                return new System.ServiceModel.EndpointAddress("http://dyolog.ddns.net:9000/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return UsuarioClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IUsuario_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return UsuarioClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IUsuario_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IUsuario_soap,
        }
    }
}
